backend:
  name: github
  repo: Francesco-Fera/mun-magazine
  branch: master
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://munmagazine.com/" # your site name

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/pages/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Titolo", name: "title", widget: "string" }
      - {
          label: "Data di Pubblicazione",
          name: "pubDate",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
        }
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "../../layouts/BlogPostLayout.astro",
        }
      - { label: "Descrizione", name: "description", widget: "string" }
      - { label: "Immagine Principale", name: "hero", widget: "image" }
      - {
          label: "Categorie",
          name: "tags",
          widget: "select",
          options: ["Cultura", "Scienza", "Politica", "Africa"],
        }
      - { label: "Autore", name: "author", widget: "string" }
      - { label: "Corpo", name: "body", widget: "markdown" }
