backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "public/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "public/images" # The src attribute for uploaded media will begin with

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/pages/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "../../layouts/BlogPostLayout.astro",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Hero Image", name: "hero", widget: "image" }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          allow_add: true,
          allow_delete: true,
        }
        { label: "Corpo", name: "body", widget: "markdown"}
